env:
  global:
  - secure: leEeanJ/EUbmaPMPzMaVf0XU6A8Vn0AX+vcfjeaOMjklDwbh/gJmBG5rfePJ0Vmnd+hOeZ0bkIsaxr0+qeep1PflK31PeneEmgOJkjwapvASOqHXQwnL6lXI4A3kbdY/JOXfJ1jfbMBWobFfeO9DbVtJFr6+zA0z4+MxYBLF5DvYw6N21IDhzRKZKWjrndHUN5XtMYbdt0+EmIuDFXeBx6szq/0GoPZ5E/zeKtVTeJzLaAPO8z/WhKKlsr/f+fdPLMqeulCQ2qb2ejd/aG7QI/Px8LPF0ymM8p1CNS5liop4akGDRKrRnCIUMk74UldJoebIOYVMBSCgERwlP0NL3UZI4KpXADv/Ngu+oH0mlhWdZEFt3sPtyW+GawJ1/Fsf/msmVxDUa59kTig5CHwUHCw6sWhZt0I+G0jvDsX76177IfaSVs5xdVKIRyHZYy/lPTfI1yx069yGh8siLOc3ix1Qtz934UR+1nMUwS7xVZixdCTdutkZyvmFWmPmvqZB9bDmx09gniY1SCSXZV1Q8AqgvgrrCjNjp61UJtNIfhPKPzqu5C4sNnuu9yE+uE/W2fBkjIN3eKYap+otvRVDtV8RBNyywfaUjhx5X7yJZR6CiW3wkyJu8LJ4OkGlK3OYqvplX+DsgOvfBT45iiTu/9OK7e69fS+MSSqAbGyU9AU=
  - secure: iEOrJoUr0FniP7Izd3+OzoslQ17DFYHtXoJRYdTuQB19CHd/2EPdnRaFUGjM7gK50XPXvDJS9OdLQ7EYeoMajNMLLIadBlf7N1/qIywdYmrYNoPAIHtwTIEHjHmWdWtHrehPmMbPhOduky9tFyAQQDCNZMSdT8hjQR7mxO2w+UsKbSLL0rBjZ/OSWqegaW7Qt/eEPIzrUwXni0eWNBSDu/V9wNWutL9lYMz8/k9yKPvFEY1W3jEiJhaPME8No8z/wJ3zaapm9ArWxdnP6al49SqcmfoIuLm/ey7n+SRrZ7TDqubpcaf8EdzlKNW3iP5wgeUWx5XdFADP0UZw+xBi29vagFX88ffqwbuaUIY/eYmPwJMYoNt6oF5r4rmogVU1Et6NbjbfrA0lnCPMTmpvXBhQcZGsF3q91WiYzcOZc4BaoOT7PzIBWQRracRcMGAAJs7JA4AMknhOxbETZ+IV5GpYoF7A5aBRF5ofVNXIpUW7ZuWj8Ukg8no3zOj60VgBdDaCsuUQn1LT1rdqHEpugszyLCuFbXvFN30rMe1xL9+KXrpGoTPwh+p6nh5DW+M9jioiqW2roKiKDwI4hmEOVVx8hItEEzI4nZvvXs6iSc9uu/y+7Ml3Vf3ka++LLa1Pu7XsalvDkPul+DfT5vqMma0huXpScEH08QP4saybu3Q=
  - secure: Ea81EosAvPTvskLoqB+CT0/p9S7KF/tCgB/c12J0I6C1fzXLa+9mKZphVvqG6wOsQ38S//sRyY1voUb2vGZPMkNuwLPT9w+/Me4wLum1wt7QrgdP4AETN+M2B2LXjT3rJFDfDuoN4CLSqFlj9qsw7skBlxaXrEJG4ADRr3y6DMj+oxKs8NCkxr7olQAKuxi4OdjXQMQkIao3tDGzyKX5zaGE44WIkHj/1/mGYhIayLO+scZm9gyGmIHGUl7EJJxxu+wAyzgmkdv5EdF4UEsHBGohzr+I9FXOABenrGs1n9o6K2JLmLFUTpV97CS6+6VTgfLfX5QbQfzUFkUtca5W8QO24Ww1ZII/BJQTi+OS6dRbRPzrMyTXtz6em2OjzT7fo5eKWd3Zw05yQ3WWFnSyWiANhpj9giJbzLhD6wtYWx7wHG1WsE2XEMpInfvxoajlsgymZc+UgXrz2EneAfr6qHOUT/3Npjn+N8cHzswzLVBK+aL6QeJiSk7knC+Q+I99cFux/WHTTnsXIcgUmFr/vJKnEHiYPYnIAaQanJ5O6/7ORB62MaF7VQdtrP36sEI3byogK5Za9mBgdgtUE6PfHFB8LOKaFBlZnlBTpgzDDUABgCqRGGCmyt/oMU96+LWGFi/l7AToBytcHfB1dKpcGq2i5xnsl4LOyYxfc7V6+cM=
  - secure: Nq1GCxxUFHmCS6WNeM8R/UZg52R7D8OTFR+NGAD8pDa2v8WG+SoGGQMHj3F3/WIid/tWT1jLbjYmZ++2cvuJjc+lGsGyCXi3FDyi4+Kp/xBpQclHEW6RhlTUL+f/zaF2CWBAmcmBBU+ckdHs/gedH0ZRWIT+zsMtu5O0BMx0PEXs5jcqYjNSHHiJn8DhZO34SKjvCrvSCrcY/etGbfvMvHaBFptJTZC/7PMGTlIQwrNhoTtdX265u3nYeyHfHeOaJGd5dkkOFuLoqWBN2uxfSd6KZrYryT8Y+wNESeklvfIg9Djsu41vEgjZVNmth08UMuZ4ZNyWzj9h7l2MNUADwdnWTIr0So4BvFrp0/XLluh9OQnyPR0VxN6V3FUpcLCsvV0fJdlZ+N+IvJg1+3DMjh34OI1s/ipCfCXEYrBQsn3fWezS8UOung56cb88Rro6TpkNbazIuVguyO0NQl0rFzyLeavd5Rd3Uz/1Z/Z3ZjWIE+xwKyd9c5UToDzhBBIZWmJfC9SivzI28oz4N09EOHhvc7osTz3R7IehdLsGcaBTrCw3rToH7rn69xwXfbMQfcxgZ/u4D9JXNtjU9Fp/sOFBBog1y/wGYjcQH6s88YNcd1cxPiLmQmuSqEfx6Cywpwc+fWyTLk6ZfTanJrozb1HrgQQVdFZr5pjZGOpOHt0=

language: php

php:
- 7.2

before_install:
- composer self-update

before_script:
- cp .env.example .env
- composer install --no-interaction
- php artisan key:generate
- mkdir -p storage/app/public/images
- php artisan storage:link
- chmod 777 -R storage
- php artisan migrate
- npm install
- npm run production

script:
- phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

services:
- mysql

cache:
  directories:
  - node_modules
  - vendor

after_success:
- curl --ftp-create-dirs
  -T filename
  --key /tmp/sftp_rsa
  sftp://${SFTP_USERNAME}:${SFTP_PASSWORD}@${SFTP_HOST}/staging