sudo: required
language: php
dist: trusty

php:
  - 7.2

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.example .env
  - php artisan key:generate

before_script:
  - mkdir -p storage/app/public/images
  - php artisan storage:link
  - chmod 777 -R storage
  - php artisan migrate
  - npm install
  - npm run production
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &
  
script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
  - php artisan dusk
  
services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

