language: php

php:
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --no-interaction
  - mkdir -p storage/app/public/images
  - php artisan key:generate
  - php artisan storage:link
  - chmod 777 -R storage
  - php artisan migrate
  - npm install
  - npm run production
  
script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
  
services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
    
env:
  - TRAVIS_NODE_VERSION="4"
