version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 81:80
        restart: always
        depends_on:
            - php
            - db
    php:
        build: .
        restart: always
        volumes:
            - .:/var/www/html
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
    selenium:
        image: selenium/standalone-chrome
        depends_on:
            - php
            - db
            - web
        restart: always
